name: Build WebGL project
on: 
  push:
    branches:
      - master
      - develop

jobs: 
  build:
    name: Build project 🤖
    runs-on: ubuntu-latest
    steps: 
      # Repo checkout
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache project data for faster reruns
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library- 

      - name: Build
        uses: game-ci/unity-builder@v2
        env: 
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          versioning: Custom
          version: Version ${{ github.sha }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: Build
          path: build